"""add monitored_accounts table

Revision ID: 9a1306627ed4
Revises: e33e7dbee181
Create Date: 2026-02-27 00:12:53.361248
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a1306627ed4'
down_revision: Union[str, None] = 'e33e7dbee181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mt5_login', sa.String(length=50), nullable=False),
    sa.Column('last_balance', sa.Float(), nullable=False),
    sa.Column('last_equity', sa.Float(), nullable=False),
    sa.Column('last_credit', sa.Float(), nullable=False),
    sa.Column('last_deal_timestamp', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monitor_reasons', sa.JSON(), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_accounts_mt5_login'), 'monitored_accounts', ['mt5_login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitored_accounts_mt5_login'), table_name='monitored_accounts')
    op.drop_table('monitored_accounts')
    # ### end Alembic commands ###
