"""Initial schema

Revision ID: e33e7dbee181
Revises: 
Create Date: 2026-02-26 23:00:04.953314
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e33e7dbee181'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CAMPAIGN_MANAGER', 'SUPPORT_AGENT', 'READ_ONLY', name='adminrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ENDED', 'ARCHIVED', name='campaignstatus'), nullable=False),
    sa.Column('bonus_type', sa.Enum('TYPE_A', 'TYPE_B', 'TYPE_C', name='bonustype'), nullable=False),
    sa.Column('bonus_percentage', sa.Float(), nullable=False),
    sa.Column('max_bonus_amount', sa.Float(), nullable=True),
    sa.Column('min_deposit', sa.Float(), nullable=True),
    sa.Column('max_deposit', sa.Float(), nullable=True),
    sa.Column('lot_requirement', sa.Float(), nullable=True),
    sa.Column('lot_tracking_scope', sa.Enum('ALL', 'POST_BONUS', 'SYMBOL_FILTERED', 'PER_TRADE_THRESHOLD', name='lottrackingscope'), nullable=True),
    sa.Column('symbol_filter', sa.JSON(), nullable=True),
    sa.Column('per_trade_lot_minimum', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_days', sa.Integer(), nullable=True),
    sa.Column('target_mt5_groups', sa.JSON(), nullable=True),
    sa.Column('target_countries', sa.JSON(), nullable=True),
    sa.Column('trigger_types', sa.JSON(), nullable=False),
    sa.Column('promo_code', sa.String(length=100), nullable=True),
    sa.Column('agent_codes', sa.JSON(), nullable=True),
    sa.Column('one_bonus_per_account', sa.Boolean(), nullable=False),
    sa.Column('max_concurrent_bonuses', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_promo_code'), 'campaigns', ['promo_code'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('mt5_login', sa.String(length=50), nullable=False),
    sa.Column('bonus_type', sa.String(length=1), nullable=False),
    sa.Column('bonus_amount', sa.Float(), nullable=False),
    sa.Column('original_leverage', sa.Integer(), nullable=True),
    sa.Column('adjusted_leverage', sa.Integer(), nullable=True),
    sa.Column('lots_required', sa.Float(), nullable=True),
    sa.Column('lots_traded', sa.Float(), nullable=False),
    sa.Column('amount_converted', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONVERTED', 'CANCELLED', 'EXPIRED', name='bonusstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonuses_campaign_id'), 'bonuses', ['campaign_id'], unique=False)
    op.create_index('ix_bonuses_campaign_status', 'bonuses', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('ix_bonuses_mt5_login'), 'bonuses', ['mt5_login'], unique=False)
    op.create_index('ix_bonuses_mt5_status', 'bonuses', ['mt5_login', 'status'], unique=False)
    op.create_index(op.f('ix_bonuses_status'), 'bonuses', ['status'], unique=False)
    op.create_table('trigger_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('mt5_login', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', 'SKIPPED', name='triggerstatus'), nullable=False),
    sa.Column('skip_reason', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_events_campaign_id'), 'trigger_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_trigger_events_mt5_login'), 'trigger_events', ['mt5_login'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'ADMIN', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('mt5_login', sa.String(length=50), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('bonus_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('ASSIGNMENT', 'CANCELLATION', 'CONVERSION_STEP', 'LEVERAGE_CHANGE', 'EXPIRY', 'ADMIN_OVERRIDE', name='eventtype'), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bonus_id'], ['bonuses.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_campaign_id'), 'audit_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_mt5_login'), 'audit_logs', ['mt5_login'], unique=False)
    op.create_table('bonus_lot_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bonus_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('lots', sa.Float(), nullable=False),
    sa.Column('amount_converted', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bonus_id'], ['bonuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_lot_progress_bonus_id'), 'bonus_lot_progress', ['bonus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bonus_lot_progress_bonus_id'), table_name='bonus_lot_progress')
    op.drop_table('bonus_lot_progress')
    op.drop_index(op.f('ix_audit_logs_mt5_login'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_campaign_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_trigger_events_mt5_login'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_campaign_id'), table_name='trigger_events')
    op.drop_table('trigger_events')
    op.drop_index(op.f('ix_bonuses_status'), table_name='bonuses')
    op.drop_index('ix_bonuses_mt5_status', table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_mt5_login'), table_name='bonuses')
    op.drop_index('ix_bonuses_campaign_status', table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_campaign_id'), table_name='bonuses')
    op.drop_table('bonuses')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_promo_code'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
